### PR TITLE
HTTP forwarded headers

### PR DESCRIPTION
**Pull request by mmatczuk**

### CODE REVIEW

**Comment by mmatczuk** [comment]
This fixes https://github.com/mmatczuk/go-http-tunnel/issues/53 by proving applications X-Forwarded-Host and X-Forwarded-Proto headers as well as disabling redirects on server.

**Comment by radutopala** [comment]
@mmatczuk now I get this `missing headers: [T-Action T-Proto T-Forwarded-For T-Forwarded-By]` for every request..

**Comment by radutopala** [comment]
@mmatczuk wait, I think I'm onto something

**Comment by radutopala** [comment]
@mmatczuk it works fine actually, great, thanks

**Comment by mmatczuk** [comment]
@goriccardo it would be actually good to add it to server to check client certificates.

**Comment by goriccardo** [comment]
I agree, I'll try to write a PR

**Pull request merged**
