### PR TITLE
Changed Go to the latest stable version on Travis.CI

### PR DESCRIPTION
**Pull request by msoap**

### CODE REVIEW

**Comment by msoap** [comment]
Perhaps need to add `- master` for run tests on the latest dev-version?

**Comment by mmatczuk** [comment]
Hi, 
maybe we could make it like https://github.com/hashicorp/consul/blob/master/.travis.yml WDYT?

**Comment by msoap** [comment]
Yes, it makes sense, for always match to current stable version. Changed PR.

**Comment by mmatczuk** [comment]
Cool, could you squash it?

**Comment by mmatczuk** [comment]
Thanks!

**Pull request merged**
