### PR TITLE
Update and lock latest go-http-tunnel dependency

### PR DESCRIPTION
**Pull request by janpieterz**
Update and explicitly set the go-http-tunnel dependency. A raw clone and dep ensure fails to build as the dependency on the project's own files fails to resolve to the latest version containing SNI protocol.

### CODE REVIEW

**Comment by mmatczuk** [comment]
How about go modules?

**Comment by janpieterz** [comment]
@mmatczuk probably a great idea, but as I'm not usually a go-developer I didn't want to venture to deep into the unknown. .

**Comment by mmatczuk** [comment]
This PR vendors itself.

**Comment by janpieterz** [comment]
Yeah, that was already the case (https://github.com/mmatczuk/go-http-tunnel/tree/f48a09d2ab15c6f4fcbeec67864d39a584f22b30/vendor/github.com), I just made it an explicit reference so in the future we can easily change it to a later version.
From a different code world it's super odd it'd reference the github repo for a reference to itself and then lock it to a version, but as I mentioned I'm not familiar so just followed whatever the latest state of the repo was.

**Comment by janpieterz** [comment]
@mmatczuk go mod method working great btw, a build from a clean repo copy worked great.

**Pull request merged**
