### PR TITLE
Added support for subscription listeners, dynamic subscription authorization and websocket support

### PR DESCRIPTION
**Pull request by ivano85**
Added support for subscription listeners, dynamic subscription authorization and websocket support

### CODE REVIEW

**Comment by ivano85** [comment]
To extend on the "websocket support", this is how I managed it in my code (instead of routing the request through server.ServeHTTP):

```go
http.HandlerFunc(func(w http.ResponseWriter, request *http.Request) {
  if request.Header.Get("Upgrade") != "" {
    buff := &bytes.Buffer{}
    request.Write(buff)
    h, ok := w.(http.Hijacker)
    if ok {
      clientConn, _, err := h.Hijack()
      if err != nil {
        fmt.Printf("Error upgrading connection: %+v\n", err)
      } else {
        clientConn.SetDeadline(time.Time{})
        id, _, _ := server.Subscriber(request.Host)
        server.Upgrade(id, clientConn, buff.Bytes())
      }
    }
  } else {
    // ... route request to server.ServeHTTP
  }
})
```

**Comment by 1ubuntuuser** [comment]
This looks nice, would you add an updated readme?

**Comment by mmatczuk** [comment]
Thanks.

**Comment by 1ubuntuuser** [comment]
@ivano85 This looks interesting. Would you be able to add some info in the readme?

**Comment by ivano85** [comment]
> @ivano85 This looks interesting. Would you be able to add some info in the readme?
> 
> Edit: if a PR is too much even explaining here how to activate this feature would be nice.

Hi, it should be sufficient to change the code on the server (ServeHTTP function) component to manage http proxy that way. I will take a look as soon as I will have enough time, but I think I cannot do it in a short time, sorry 😔...

**Pull request merged**
